// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Skill struct {
	ID        interface{}
	Title     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID        interface{}
	Username  string
	FirstName string
	LastName  string
	Email     string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Address   interface{}
}

type UserSkill struct {
	UserID  interface{}
	SkillID interface{}
}
